from setuptools import setup

setup(
    name="sts-pylib",
    version="0.0.2",
    description="Functional interface to the NIST randomness tests",
    long_description=open("README.md").read(),
    long_description_content_type="text/markdown",
    author="Matthew Barber",
    author_email="quitesimplymatt@gmail.com",
    url="https://github.com/Honno/sts-pylib",
    include_package_data=True,
    packages = ["."],
    project_urls={
        "Documentation": "https://sts-pylib.readthedocs.io/",
        "Issue Tracker": "https://github.com/Honno/sts-pylib/issues",
    },
    py_modules=["sts"],
    cffi_modules=["ext_build.py:ffi"],
    install_requires=["cffi>=1.0.0"],
    setup_requires=["cffi>=1.0.0"],
    classifiers=[
        "Development Status :: 3 - Alpha",
        "Intended Audience :: Developers",
        "Operating System :: Unix",
        "Operating System :: POSIX",
        "Operating System :: MacOS",
        "Operating System :: Microsoft :: Windows",
        "Programming Language :: Python",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.6",
        "Programming Language :: Python :: 3.7",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: Implementation :: CPython",
        "License :: OSI Approved :: BSD License",
        "Topic :: Security :: Cryptography",
        "Topic :: Software Development :: Libraries",
    ],
    keywords=["rng", "prng", "randomness", "nist", "sts", "statistics", "tests", "randomness-testing", "cryptography", "data-science"],
)
